spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.tmxf.domain
  #mapper-locations: classpath:mapper/*.xml
server:
  port: 8000